<script lang="ts">
  import { base } from '$app/paths';
</script>

<svelte:head>
  <title>Terms & Conditions | Multilingual Lorem Generator</title>
  <meta name="description" content="Open-source, free to use, no restrictions. Use it personally or commercially — forever." />
  <meta property="og:title" content="Terms & Conditions — Multilingual Lorem Generator" />
  <meta property="og:description" content="MIT licensed. No attribution required. Use anywhere." />
  <meta property="og:url" content="{base}/terms" />
  <meta property="og:type" content="website" />
  <meta name="twitter:card" content="summary_large_image" />
</svelte:head>

<div class="container fade-in post-layout">
  <div class="breadcrumbs">
    <a href="{base}/">Home</a>
    <span>/</span>
    <p>Terms & Conditions</p>
  </div>

  <article class="prose">
    <h1>Terms & Conditions</h1>
    <p class="post-meta">Last Updated: November 27, 2025</p>

    <p>By using the <strong>Multilingual Lorem Placeholder Text Generator</strong> (“the Tool”), you agree to these Terms. The Tool is free, open-source software released under the <strong>MIT License</strong>.</p>

    <h2>1. Use of the Tool</h2>
    <p>You may use the Tool for any purpose — personal, educational, commercial, or enterprise — without restriction. There are no usage limits, no accounts, and no paywalls.</p>

    <h2>2. License</h2>
    <p>The Tool is licensed under the <strong>MIT License</strong>. This means:</p>
    <ul>
      <li>You can use it in client projects</li>
      <li>You can modify and redistribute it</li>
      <li>You can host it on your own domain</li>
      <li><strong>No attribution is required</strong> (though appreciated)</li>
      <li>You can use it in proprietary or closed-source projects</li>
    </ul>

    <h2>3. No Warranty</h2>
    <p>The Tool is provided “<em>as is</em>” without warranty of any kind, express or implied. We do not guarantee it will be error-free, secure, or suitable for your specific use case.</p>

    <h2>4. Limitation of Liability</h2>
    <p>In no event shall the authors or contributors be liable for any damages arising from the use or inability to use the Tool — even if advised of the possibility.</p>

    <h2>5. Content Generated</h2>
    <p>All text generated by the Tool is <strong>public domain</strong> or <strong>CC0</strong>. You may use it freely in designs, websites, apps, presentations, or print materials without credit.</p>

    <h2>6. Modifications & Forks</h2>
    <p>You are encouraged to fork, improve, or customize the Tool. If you redistribute a modified version, you must include the original MIT license and copyright notice.</p>

    <h2>7. Hosting & Distribution</h2>
    <p>You may host the Tool on GitHub Pages, Netlify, Vercel, company intranet, or anywhere else. No permission needed.</p>

    <h2>8. Termination</h2>
    <p>We reserve the right to discontinue the public instance at any time (though the code will remain available on GitHub).</p>

    <h2>9. Governing Law</h2>
    <p>These Terms are governed by the laws of open-source goodwill and common sense.</p>

    <p class="italic-note">This isn’t legal boilerplate — it’s a promise: <strong>use this tool freely, safely, and without worry.</strong> That’s all we ask in return.</p>
  </article>
</div>

<style>
  .post-layout { max-width: 800px; margin: 0 auto; padding: 2rem 1rem 5rem; }
  .breadcrumbs { display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1.5rem; font-size: 0.9rem; color: #666; }
  .breadcrumbs a { color: #0066cc; text-decoration: none; }
  .breadcrumbs a:hover { text-decoration: underline; }
  .prose { line-height: 1.8; }
  .prose .post-meta { color: #666; font-size: 0.9rem; margin-bottom: 2rem; border-bottom: 1px solid #eee; padding-bottom: 1rem; }
  .prose h1 { font-size: 2.8rem; margin-bottom: 0.5rem; color: #1a1a1a; }
  .prose h2 { margin-top: 2.8rem; color: #0066cc; border-bottom: 1px solid #f0f0f0; padding-bottom: 0.5rem; }
  .prose ul { padding-left: 1.6rem; margin: 1.2rem 0; }
  .prose ul li::marker { color: #0066cc; }
  .prose em { color: #d73a9d7; font-style: normal; }
  .prose .italic-note { font-style: italic; text-align: center; margin-top: 4rem; font-size: 1.1rem; color: #555; }
</style>